/**
 * Data loading utilities for the policy tracker.
 * Reads JSON files generated by the Python fetch scripts.
 */

import fs from 'node:fs';
import path from 'node:path';

const DATA_DIR = path.join(process.cwd(), 'data');

export interface PolicyItem {
  id: string;
  title: string;
  description: string;
  link: string;
  date: string;
  source_id: string;
  source_name: string;
  source_short: string;
  sectors: string[];
  sector_slugs: string[];
  type: string;
}

export interface MetaData {
  last_updated: string;
  total_policies: number;
  total_sources: number;
  total_sectors: number;
  sector_counts: Record<string, number>;
  source_counts: Record<string, number>;
}

function readJson<T>(filename: string, fallback: T): T {
  const filepath = path.join(DATA_DIR, filename);
  try {
    const raw = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function getAllPolicies(): PolicyItem[] {
  return readJson<PolicyItem[]>('policies.json', getSamplePolicies());
}

export function getMeta(): MetaData {
  const policies = getAllPolicies();
  const sectorCounts: Record<string, number> = {};
  const sourceCounts: Record<string, number> = {};

  for (const p of policies) {
    for (const s of p.sectors) {
      sectorCounts[s] = (sectorCounts[s] || 0) + 1;
    }
    sourceCounts[p.source_short] = (sourceCounts[p.source_short] || 0) + 1;
  }

  const stored = readJson<Partial<MetaData>>('meta.json', {});
  return {
    last_updated: stored.last_updated || new Date().toISOString(),
    total_policies: policies.length,
    total_sources: Object.keys(sourceCounts).length,
    total_sectors: Object.keys(sectorCounts).length,
    sector_counts: sectorCounts,
    source_counts: sourceCounts,
  };
}

export function getPoliciesBySector(sectorSlug: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.sector_slugs.includes(sectorSlug));
}

export function getPoliciesBySource(sourceShort: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.source_short === sourceShort);
}

export function getSectorSlug(sector: string): string {
  return sector.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
}

export function getAllSectorSlugs(): string[] {
  const meta = getMeta();
  return Object.keys(meta.sector_counts).map(getSectorSlug);
}

export function getAllSourceShorts(): string[] {
  const meta = getMeta();
  return Object.keys(meta.source_counts);
}

/**
 * Sample/seed data so the site builds even before first fetch
 */
function getSamplePolicies(): PolicyItem[] {
  return [
    {
      id: "sample001",
      title: "Union Budget 2026-27: Key Highlights for Development Sectors",
      description: "The Finance Minister presented the Union Budget with significant allocations for education, health, rural development and digital infrastructure.",
      link: "https://www.indiabudget.gov.in/",
      date: "2026-02-01",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Finance & Economy", "Education", "Health"],
      sector_slugs: ["finance-economy", "education", "health"],
      type: "budget"
    },
    {
      id: "sample002",
      title: "National Education Policy Implementation: Progress Report 2026",
      description: "NITI Aayog releases comprehensive assessment of NEP 2020 implementation covering curriculum reforms, teacher training, and higher education restructuring.",
      link: "https://www.niti.gov.in/",
      date: "2026-01-15",
      source_id: "niti_aayog",
      source_name: "NITI Aayog",
      source_short: "NITI",
      sectors: ["Education", "Governance & Reform"],
      sector_slugs: ["education", "governance-reform"],
      type: "research"
    },
    {
      id: "sample003",
      title: "Digital Personal Data Protection Rules 2026 Notified",
      description: "The Ministry of Electronics and IT notifies the final rules under the Digital Personal Data Protection Act, 2023 covering consent, data fiduciary obligations, and cross-border data flows.",
      link: "https://www.meity.gov.in/",
      date: "2026-01-20",
      source_id: "meity",
      source_name: "Ministry of Electronics and IT",
      source_short: "MeitY",
      sectors: ["Digital & Technology", "Governance & Reform"],
      sector_slugs: ["digital-technology", "governance-reform"],
      type: "notification"
    },
    {
      id: "sample004",
      title: "PM-KISAN: 18th Instalment Released Benefiting 9 Crore Farmers",
      description: "The 18th instalment under the Pradhan Mantri Kisan Samman Nidhi has been released, directly transferring funds to eligible farmer families across the country.",
      link: "https://www.pib.gov.in/",
      date: "2026-02-15",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Agriculture", "Social Protection"],
      sector_slugs: ["agriculture", "social-protection"],
      type: "scheme"
    },
    {
      id: "sample005",
      title: "Jal Jeevan Mission: 90% Rural Households Now Have Tap Water Connections",
      description: "The Jal Jeevan Mission crosses a major milestone with 90% of rural households now having functional household tap water connections.",
      link: "https://jaljeevanmission.gov.in/",
      date: "2026-02-20",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Water & Sanitation", "Rural Development"],
      sector_slugs: ["water-sanitation", "rural-development"],
      type: "announcement"
    },
    {
      id: "sample006",
      title: "India's Updated Nationally Determined Contribution Under Paris Agreement",
      description: "India submits its updated NDC to the UNFCCC, enhancing climate targets including 50% non-fossil fuel energy capacity by 2030 and net-zero by 2070.",
      link: "https://moef.gov.in/",
      date: "2026-01-25",
      source_id: "moefcc",
      source_name: "Ministry of Environment",
      source_short: "MoEFCC",
      sectors: ["Climate & Environment", "Energy"],
      sector_slugs: ["climate-environment", "energy"],
      type: "policy"
    },
    {
      id: "sample007",
      title: "RBI Monetary Policy: Repo Rate Cut to Support Growth",
      description: "The Reserve Bank of India's Monetary Policy Committee announces a 25 basis point reduction in the repo rate, citing easing inflation and the need to support economic growth.",
      link: "https://rbi.org.in/",
      date: "2026-02-07",
      source_id: "rbi",
      source_name: "Reserve Bank of India",
      source_short: "RBI",
      sectors: ["Finance & Economy"],
      sector_slugs: ["finance-economy"],
      type: "announcement"
    },
    {
      id: "sample008",
      title: "Labour Codes Implementation: Final Notification for Code on Social Security",
      description: "The Ministry of Labour and Employment issues the final notification for implementing the Code on Social Security 2020, covering gig workers and platform workers for the first time.",
      link: "https://labour.gov.in/",
      date: "2026-01-10",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Labour & Employment", "Social Protection", "Digital & Technology"],
      sector_slugs: ["labour-employment", "social-protection", "digital-technology"],
      type: "legislation"
    },
    {
      id: "sample009",
      title: "Women's Reservation Act: Delimitation Commission Progress Update",
      description: "PRS Legislative Research analysis of the implementation timeline for the Women's Reservation Act following the Census and delimitation exercise.",
      link: "https://prsindia.org/",
      date: "2026-02-10",
      source_id: "prs_legislative",
      source_name: "PRS Legislative Research",
      source_short: "PRS",
      sectors: ["Gender & Women", "Governance & Reform"],
      sector_slugs: ["gender-women", "governance-reform"],
      type: "research"
    },
    {
      id: "sample010",
      title: "India Semiconductor Mission: Three New Fab Units Approved",
      description: "The Cabinet approves establishment of three new semiconductor fabrication units under the India Semiconductor Mission with a combined investment of Rs 1.5 lakh crore.",
      link: "https://www.meity.gov.in/",
      date: "2026-02-25",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Digital & Technology", "Science & Innovation", "Trade & Commerce"],
      sector_slugs: ["digital-technology", "science-innovation", "trade-commerce"],
      type: "announcement"
    }
  ];
}
