/**
 * Data loading utilities for the policy tracker.
 * Reads JSON files generated by the Python fetch scripts.
 */

import fs from 'node:fs';
import path from 'node:path';

const DATA_DIR = path.join(process.cwd(), 'data');

export interface PolicyItem {
  id: string;
  title: string;
  description: string;
  link: string;
  date: string;
  source_id: string;
  source_name: string;
  source_short: string;
  sectors: string[];
  sector_slugs: string[];
  type: string;
  level?: string;  // 'central' or 'state'
  state?: string;  // state name if level === 'state'
}

export interface MetaData {
  last_updated: string;
  total_policies: number;
  total_sources: number;
  total_sectors: number;
  sector_counts: Record<string, number>;
  source_counts: Record<string, number>;
}

function readJson<T>(filename: string, fallback: T): T {
  const filepath = path.join(DATA_DIR, filename);
  try {
    const raw = fs.readFileSync(filepath, 'utf-8');
    return JSON.parse(raw) as T;
  } catch {
    return fallback;
  }
}

export function getAllPolicies(): PolicyItem[] {
  return readJson<PolicyItem[]>('policies.json', getSamplePolicies());
}

export function getMeta(): MetaData {
  const policies = getAllPolicies();
  const sectorCounts: Record<string, number> = {};
  const sourceCounts: Record<string, number> = {};

  for (const p of policies) {
    for (const s of p.sectors) {
      sectorCounts[s] = (sectorCounts[s] || 0) + 1;
    }
    sourceCounts[p.source_short] = (sourceCounts[p.source_short] || 0) + 1;
  }

  const stored = readJson<Partial<MetaData>>('meta.json', {});
  return {
    last_updated: stored.last_updated || new Date().toISOString(),
    total_policies: policies.length,
    total_sources: Object.keys(sourceCounts).length,
    total_sectors: Object.keys(sectorCounts).length,
    sector_counts: sectorCounts,
    source_counts: sourceCounts,
  };
}

export function getPoliciesBySector(sectorSlug: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.sector_slugs.includes(sectorSlug));
}

export function getPoliciesBySource(sourceShort: string): PolicyItem[] {
  return getAllPolicies().filter(p => p.source_short === sourceShort);
}

export function getSectorSlug(sector: string): string {
  return sector.toLowerCase().replace(/ & /g, '-').replace(/ /g, '-');
}

export function getAllSectorSlugs(): string[] {
  const meta = getMeta();
  return Object.keys(meta.sector_counts).map(getSectorSlug);
}

export function getAllSourceShorts(): string[] {
  const meta = getMeta();
  return Object.keys(meta.source_counts);
}

export function getPolicyById(id: string): PolicyItem | undefined {
  return getAllPolicies().find(p => p.id === id);
}

export function getRelatedPolicies(policy: PolicyItem, limit = 5): PolicyItem[] {
  const all = getAllPolicies();
  return all
    .filter(p => p.id !== policy.id && p.sector_slugs.some(s => policy.sector_slugs.includes(s)))
    .slice(0, limit);
}

/** Returns { 'YYYY-MM-DD': count } for the heatmap */
export function getDailyActivity(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const p of getAllPolicies()) {
    counts[p.date] = (counts[p.date] || 0) + 1;
  }
  return counts;
}

/** Returns { 'YYYY-WW': count } for weekly trends */
export function getWeeklyTrends(): { week: string; count: number }[] {
  const weekly: Record<string, number> = {};
  for (const p of getAllPolicies()) {
    const d = new Date(p.date);
    const year = d.getFullYear();
    const jan1 = new Date(year, 0, 1);
    const weekNum = Math.ceil(((d.getTime() - jan1.getTime()) / 86400000 + jan1.getDay() + 1) / 7);
    const key = `${year}-W${String(weekNum).padStart(2, '0')}`;
    weekly[key] = (weekly[key] || 0) + 1;
  }
  return Object.entries(weekly)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([week, count]) => ({ week, count }));
}

/** Returns type distribution */
export function getTypeDistribution(): { type: string; count: number; pct: number }[] {
  const types: Record<string, number> = {};
  const all = getAllPolicies();
  for (const p of all) {
    types[p.type] = (types[p.type] || 0) + 1;
  }
  return Object.entries(types)
    .sort(([, a], [, b]) => b - a)
    .map(([type, count]) => ({ type, count, pct: Math.round((count / all.length) * 100) }));
}

/** Returns top N most active sectors */
export function getTopSectors(n = 6): { sector: string; slug: string; count: number }[] {
  const meta = getMeta();
  return Object.entries(meta.sector_counts)
    .sort(([, a], [, b]) => b - a)
    .slice(0, n)
    .map(([sector, count]) => ({ sector, slug: getSectorSlug(sector), count }));
}

/** Returns a structured insight for a given sector */
export interface SectorInsight {
  name: string;
  slug: string;
  total: number;
  recentCount: number; // last 30 days
  typeBreakdown: { type: string; count: number }[];
  topSources: { source: string; count: number }[];
  latestPolicy: PolicyItem | null;
  relatedSectors: string[]; // sectors that co-occur most
}

export function getSectorInsight(sectorName: string): SectorInsight {
  const slug = getSectorSlug(sectorName);
  const policies = getPoliciesBySector(slug);
  const now = Date.now();
  const DAY = 86400000;

  // Type breakdown
  const types: Record<string, number> = {};
  for (const p of policies) types[p.type] = (types[p.type] || 0) + 1;
  const typeBreakdown = Object.entries(types)
    .sort(([, a], [, b]) => b - a)
    .map(([type, count]) => ({ type, count }));

  // Top sources
  const sources: Record<string, number> = {};
  for (const p of policies) sources[p.source_short] = (sources[p.source_short] || 0) + 1;
  const topSources = Object.entries(sources)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 3)
    .map(([source, count]) => ({ source, count }));

  // Related sectors (co-occurrence)
  const coSectors: Record<string, number> = {};
  for (const p of policies) {
    for (const s of p.sectors) {
      if (s !== sectorName) coSectors[s] = (coSectors[s] || 0) + 1;
    }
  }
  const relatedSectors = Object.entries(coSectors)
    .sort(([, a], [, b]) => b - a)
    .slice(0, 4)
    .map(([s]) => s);

  return {
    name: sectorName,
    slug,
    total: policies.length,
    recentCount: policies.filter(p => now - new Date(p.date).getTime() < 30 * DAY).length,
    typeBreakdown,
    topSources,
    latestPolicy: policies[0] || null,
    relatedSectors,
  };
}

/** Returns policy count by government era */
export function getEraDistribution(): { era: string; party: string; count: number; dateRange: string }[] {
  const eras = [
    { name: 'UPA I',   party: 'Congress-led UPA',  start: '2004-05-22', end: '2009-05-21' },
    { name: 'UPA II',  party: 'Congress-led UPA',  start: '2009-05-22', end: '2014-05-25' },
    { name: 'NDA I',   party: 'BJP-led NDA',       start: '2014-05-26', end: '2019-05-29' },
    { name: 'NDA II',  party: 'BJP-led NDA',       start: '2019-05-30', end: '2024-06-08' },
    { name: 'NDA III', party: 'BJP-led NDA',       start: '2024-06-09', end: '9999-12-31' },
  ];
  const all = getAllPolicies();
  return eras.map(era => ({
    era: era.name,
    party: era.party,
    count: all.filter(p => p.date >= era.start && p.date <= era.end).length,
    dateRange: `${era.start.slice(0,4)}–${era.end === '9999-12-31' ? 'Present' : era.end.slice(0,4)}`,
  }));
}

/** Returns sectors x types matrix for landscape view */
export function getSectorTypeMatrix(): {
  sectors: string[];
  types: string[];
  matrix: Record<string, Record<string, number>>;
} {
  const all = getAllPolicies();
  const sectorSet = new Set<string>();
  const typeSet = new Set<string>();
  const matrix: Record<string, Record<string, number>> = {};

  for (const p of all) {
    typeSet.add(p.type);
    for (const s of p.sectors) {
      sectorSet.add(s);
      if (!matrix[s]) matrix[s] = {};
      matrix[s][p.type] = (matrix[s][p.type] || 0) + 1;
    }
  }

  const meta = getMeta();
  const sectors = Object.entries(meta.sector_counts)
    .sort(([, a], [, b]) => b - a)
    .map(([s]) => s);

  const types = ['legislation', 'notification', 'scheme', 'budget', 'research', 'announcement', 'policy']
    .filter(t => typeSet.has(t));

  return { sectors, types, matrix };
}

/**
 * Sample/seed data so the site builds even before first fetch
 */
function getSamplePolicies(): PolicyItem[] {
  return [
    {
      id: "sample001",
      title: "Union Budget 2026-27: Key Highlights for Development Sectors",
      description: "The Finance Minister presented the Union Budget with significant allocations for education, health, rural development and digital infrastructure.",
      link: "https://www.indiabudget.gov.in/",
      date: "2026-02-01",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Finance & Economy", "Education", "Health"],
      sector_slugs: ["finance-economy", "education", "health"],
      type: "budget"
    },
    {
      id: "sample002",
      title: "National Education Policy Implementation: Progress Report 2026",
      description: "NITI Aayog releases comprehensive assessment of NEP 2020 implementation covering curriculum reforms, teacher training, and higher education restructuring.",
      link: "https://www.niti.gov.in/",
      date: "2026-01-15",
      source_id: "niti_aayog",
      source_name: "NITI Aayog",
      source_short: "NITI",
      sectors: ["Education", "Governance & Reform"],
      sector_slugs: ["education", "governance-reform"],
      type: "research"
    },
    {
      id: "sample003",
      title: "Digital Personal Data Protection Rules 2026 Notified",
      description: "The Ministry of Electronics and IT notifies the final rules under the Digital Personal Data Protection Act, 2023 covering consent, data fiduciary obligations, and cross-border data flows.",
      link: "https://www.meity.gov.in/",
      date: "2026-01-20",
      source_id: "meity",
      source_name: "Ministry of Electronics and IT",
      source_short: "MeitY",
      sectors: ["Digital & Technology", "Governance & Reform"],
      sector_slugs: ["digital-technology", "governance-reform"],
      type: "notification"
    },
    {
      id: "sample004",
      title: "PM-KISAN: 18th Instalment Released Benefiting 9 Crore Farmers",
      description: "The 18th instalment under the Pradhan Mantri Kisan Samman Nidhi has been released, directly transferring funds to eligible farmer families across the country.",
      link: "https://www.pib.gov.in/",
      date: "2026-02-15",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Agriculture", "Social Protection"],
      sector_slugs: ["agriculture", "social-protection"],
      type: "scheme"
    },
    {
      id: "sample005",
      title: "Jal Jeevan Mission: 90% Rural Households Now Have Tap Water Connections",
      description: "The Jal Jeevan Mission crosses a major milestone with 90% of rural households now having functional household tap water connections.",
      link: "https://jaljeevanmission.gov.in/",
      date: "2026-02-20",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Water & Sanitation", "Rural Development"],
      sector_slugs: ["water-sanitation", "rural-development"],
      type: "announcement"
    },
    {
      id: "sample006",
      title: "India's Updated Nationally Determined Contribution Under Paris Agreement",
      description: "India submits its updated NDC to the UNFCCC, enhancing climate targets including 50% non-fossil fuel energy capacity by 2030 and net-zero by 2070.",
      link: "https://moef.gov.in/",
      date: "2026-01-25",
      source_id: "moefcc",
      source_name: "Ministry of Environment",
      source_short: "MoEFCC",
      sectors: ["Climate & Environment", "Energy"],
      sector_slugs: ["climate-environment", "energy"],
      type: "policy"
    },
    {
      id: "sample007",
      title: "RBI Monetary Policy: Repo Rate Cut to Support Growth",
      description: "The Reserve Bank of India's Monetary Policy Committee announces a 25 basis point reduction in the repo rate, citing easing inflation and the need to support economic growth.",
      link: "https://rbi.org.in/",
      date: "2026-02-07",
      source_id: "rbi",
      source_name: "Reserve Bank of India",
      source_short: "RBI",
      sectors: ["Finance & Economy"],
      sector_slugs: ["finance-economy"],
      type: "announcement"
    },
    {
      id: "sample008",
      title: "Labour Codes Implementation: Final Notification for Code on Social Security",
      description: "The Ministry of Labour and Employment issues the final notification for implementing the Code on Social Security 2020, covering gig workers and platform workers for the first time.",
      link: "https://labour.gov.in/",
      date: "2026-01-10",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Labour & Employment", "Social Protection", "Digital & Technology"],
      sector_slugs: ["labour-employment", "social-protection", "digital-technology"],
      type: "legislation"
    },
    {
      id: "sample009",
      title: "Women's Reservation Act: Delimitation Commission Progress Update",
      description: "PRS Legislative Research analysis of the implementation timeline for the Women's Reservation Act following the Census and delimitation exercise.",
      link: "https://prsindia.org/",
      date: "2026-02-10",
      source_id: "prs_legislative",
      source_name: "PRS Legislative Research",
      source_short: "PRS",
      sectors: ["Gender & Women", "Governance & Reform"],
      sector_slugs: ["gender-women", "governance-reform"],
      type: "research"
    },
    {
      id: "sample010",
      title: "India Semiconductor Mission: Three New Fab Units Approved",
      description: "The Cabinet approves establishment of three new semiconductor fabrication units under the India Semiconductor Mission with a combined investment of Rs 1.5 lakh crore.",
      link: "https://www.meity.gov.in/",
      date: "2026-02-25",
      source_id: "pib",
      source_name: "Press Information Bureau",
      source_short: "PIB",
      sectors: ["Digital & Technology", "Science & Innovation", "Trade & Commerce"],
      sector_slugs: ["digital-technology", "science-innovation", "trade-commerce"],
      type: "announcement"
    }
  ];
}
